### ISSUE TITLE
friendly_name_template

### ISSUE THREAD

**Issue by julinhosf** [snarky-snark/home-assistant-variables#65] opened 2022-03-19 22:14 UTC
Hi, I'm trying to use friendly_name_template but it doesn't seem to work properly. The friendly name doesn't change.
Am I doing anything wrong?, does it works?
Thanks for this great integration!

**Comment by javilopezalarcon** [comment] 2022-03-22 21:36
hello I have the same problem, I need to change the friendly names and I have tried with fryendly name, friendly name template and yes, I make it work, but when restarting it returns to the state it was in, it does not save the value. it's like the restore option doesn't work on friendly names. the other variables that I have tried work perfectly, only the friendly name fails me. thanks for the integration, it's wonderful, let's see if we can fix this, anything you need from me let me know. a greeting

**Comment by snarky-snark** [comment] 2022-03-22 21:52
`friendly_name_template`, like all template attributes, is only evaluated when a tracked event occurs or a tracked entity's state changes. To evaluate the template each time home assistant starts, include the `home_assisstant_start` event in `tracked_event_type`.

Use can use `var.set` and the HA developer tools to manually set attributes if you have already created the variable and only need to set the attribute once.

**Comment by javilopezalarcon** [comment] 2022-03-22 22:18
I'm sorry, I haven't fully understood you (I use a translator) I'm making 12 sensors in a chain where the next one takes the friendly name of the previous one, to monitor monthly electricity consumption... the last one takes the consumption value of this month in course and the friendly name of a sensor that indicates what month we are in, the previous sensor, take the value that the previous one had and the friendly name too, which would be from the previous month... but they save the consumption values ​​well, but when restarting home assistant, I lose everyone's friendly name, I do it as follows:
 ......

  - service: var.set
    data:
      entity_id: var.consumo_mes_1
      value_template: '{{states ("sensor.luz_mensual_plana")}}'
      friendly_name: Consumo {{states("sensor.month_name")}}
  mode: single

As I understand you, it would be to declare in the variable sensor: 
var: 
  consumption_month_1:
   tracked_event_type: home_assistant.start

 I think the mistake was not saying that I was trying it in an automation, right?

**Comment by snarky-snark** [comment] 2022-03-22 22:30
Yes, I think you could do it that way.

**Comment by snarky-snark** [comment] 2022-03-22 22:35
To be clear, the event is `home_assisstant_start`, not `home_assisstant_start.start`

**Comment by javilopezalarcon** [comment] 2022-03-22 22:47
Well, it doesn't work for me, adding that to the config.yaml, home_assistant_start, does the same, runs the automation, changes the value and the friendly_name, but when restarting home Assistant the value of the sensor keeps it but the friendly_name doesn't, it loses it.

**Comment by snarky-snark** [comment] 2022-03-22 22:58
I may be misunderstanding what you are trying to accomplish. Your automation sounds complex. I would try some simple isolated tests to verify the behavior.

How are you defining variables?

**Comment by javilopezalarcon** [comment] 2022-03-22 23:04
Only 
var:
  sensor_mes_1:
  sensor_mes_2:
  sensor_mes_3:
…

and i just need to change the value and the friendlyname, the value changes it fine, but the friendly_name, when restarting home assistant, it loses it

**Comment by snarky-snark** [comment] 2022-03-22 23:12
I see. Entity attributes must not be saved across restarts. I thought they were, but I might be misremebering.

Another approach is to use a separate variable for the month.

**Comment by javilopezalarcon** [comment] 2022-03-22 23:19
Exactly, it does not save it after the restart... I have also thought about using one for the month and another for the value, but it was necessary to make it cleaner... for example, when doing it in a bar graph for example, it would be better than the January sensor has 200 for example, March sensor 180, etc.. if that cannot be done, I will give it another go to see how I could get it to be as clean as possible. thank you very much for your help

**Comment by snarky-snark** [comment] 2022-03-22 23:55
Another compromise would be to store the month name in a second variable, and set the first variable friendly name using the value of the second variable via a template and the home assistant start event.

It's kludgey, but I think it would work.

**Comment by snarky-snark** [comment] 2022-03-29 15:31
Duplicate of #34.

**Closed as completed by snarky-snark** 2022-03-29 15:31 UTC
