### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by NotSteveAtGithub** [snarky-snark/home-assistant-variables#6] opened 2019-08-31 00:39 UTC
I've tested with and without "var:" in configuration.yaml.  With it enabled, this error is logged:

2019-08-30 19:30:17 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 223, in async_setup_platform
    self.hass, self.config, self.domain, platform_type
  File "/usr/src/homeassistant/homeassistant/setup.py", line 227, in async_prepare_setup_platform
    integration = await loader.async_get_integration(hass, platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 283, in async_get_integration
    Integration.resolve_from_root, hass, components, domain
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 154, in resolve_from_root
    manifest_path = pathlib.Path(base) / domain / "manifest.json"
  File "/usr/local/lib/python3.7/pathlib.py", line 908, in __truediv__
    return self._make_child((key,))
  File "/usr/local/lib/python3.7/pathlib.py", line 695, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.7/pathlib.py", line 649, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by snarky-snark** [comment] 2019-08-31 01:01
Thanks for the report! I'll take a look. Just to note, this isn't causing any noticeable issues apart from the error message itself, correct?

**Comment by NotSteveAtGithub** [comment] 2019-08-31 01:02
Correct - everything seems to be functioning well.  Thanks!

**Comment by genem2** [comment] 2019-09-03 16:19
Same here. 
I am lovin' this component, with the automatic updating and all. Should serve as a model for all HA entities!

**Comment by Swiftnesses** [comment] 2019-10-06 08:11
I also see this, any update?

**Comment by GoNzCiD** [comment] 2019-10-16 19:41
Same here!, I had noticed this error on my HA log, but till now I have not discovered it's from `vars`.

Apart from this error, all seems to works.

I can see it's labeled with 0.7.0. I'm running v0.8.0.

**Comment by froz** [comment] 2019-10-31 20:44
~~It's caused by the 'dependencies: ["recorder"],' in manifest.json.  Changing it to 'dependencies: [],'  avoids the error.  I don't remember if the recorder is enabled by default.~~

Nevermind.  It's back on the second reboot.  Must have been a fluke that it didn't show up once.

**Comment by GoNzCiD** [comment] 2019-11-04 11:10
> 
> 
> ~It's caused by the 'dependencies: ["recorder"],' in manifest.json. Changing it to 'dependencies: [],' avoids the error. I don't remember if the recorder is enabled by default.~
> 
> Nevermind. It's back on the second reboot. Must have been a fluke that it didn't show up once.

I have tested it with similar result... In my case the error is logged in the first reboot.

**Comment by snarky-snark** [comment] 2019-11-23 19:56
I've walked through the HA source code (and custom component documentation) in an attempt to figure this one out, but I'm at a loss.

This component is fairly simple, yet it's difficult to point to any one piece of it that could be causing the problem.

I had been suspicious of the dependency on the recorder, but as some of you have noted, that doesn't appear to be the source of the error.

My only other guess at this point is that there is some fundamental misuse of the HA custom component API, but the developer docs haven't been helpful in illuminating much that I should be doing differently.

Since this issue doesn't appear to be causing any issues apart from a seemingly benign error message, I'm inclined to let it sit here until someone comes along with new information.

**Comment by froz** [comment] 2019-12-10 16:21
The error is caused by not setting the platform for variables.  I'm not positive, but you may need to wrap the async_add_entities call in an async_add_platform function.

**Comment by snarky-snark** [comment] 2019-12-10 16:49
This confuses me, because I thought it was possible to create an integration that is not a platform (thus no need to set the platform). Perhaps, I'm wrong. I haven't been able to find any good examples of components setting the platform.

**Comment by froz** [comment] 2019-12-10 16:57
I don't know, but looking at the output of pysnooper, I can see that this is the only platform_type = None.  The Variable component is OK, its the variables created that have the error, such as my var.nighttime

Below, the platform_type should be platform_type = 'var' and The platform_config should be like OrderedDict([('platform', 'nighttime' ...

```
Source path:... /usr/src/homeassistant/homeassistant/helpers/entity_component.py
New var:....... self = <homeassistant.helpers.entity_component.EntityComponent object at 0x7f7ac00610>
New var:....... platform_type = None
New var:....... platform_config = OrderedDict([('nighttime', OrderedDict([('friend...'binary_sensor.night', 'binary_sens
New var:....... discovery_info = None
```

**Comment by snarky-snark** [comment] 2019-12-10 16:59
Ah, this is helpful. Thanks! I'll try to set the platform and see if that clears things up.

**Comment by smhgit** [comment] 2020-01-19 12:25
Same issue
```
2020-01-19 14:21:36 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 214, in async_setup_platform
    self.hass, self.config, self.domain, platform_type
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in async_prepare_setup_platform
    integration = await loader.async_get_integration(hass, platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 311, in async_get_integration
    Integration.resolve_from_root, hass, components, domain
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 154, in resolve_from_root
    manifest_path = pathlib.Path(base) / domain / "manifest.json"
  File "/usr/local/lib/python3.7/pathlib.py", line 920, in __truediv__
    return self._make_child((key,))
  File "/usr/local/lib/python3.7/pathlib.py", line 699, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.7/pathlib.py", line 653, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by jazzyisj** [comment] 2020-01-22 19:37
@snarky-snark   I see you've closed this but I still get it on every reboot.  I'm updated to v0.104.3 and home-assistant-variables is v0.9.2

**Comment by snarky-snark** [comment] 2020-01-22 19:45
> @snarky-snark I see you've closed this but I still get it on every reboot. I'm updated to v0.104.3 and home-assistant-variables is v0.9.2

On the contrary, this ticket is very much open. I still haven't identified the source of the issue, but since it doesn't appear to be causing any problems other than the log message and I'm not exactly being paid for my efforts, I can't say it's a high priority for me at this time.

**Comment by jazzyisj** [comment] 2020-01-22 20:06
No worries my friend.  I saw the closed notice on the Reserved Words issue and had a brain fart.

Great integration BTW.   Really cleaned up some of my config, so thanks!  Makes you wonder why it wasn't included in the first place!

**Comment by snarky-snark** [comment] 2020-01-22 20:17
Thanks! Glad you have found it useful.

Yeah, I initially built this component to clean up my own config. I can say, I'm not a fan of YAML for automations, and I was hoping this component would make it easier to work with.

These days, though, I mostly use NodeRed for my own automations as I don't find YAML worth the headache. It's really not designed for what HA uses it for.

**Comment by jacekpaszkowski** [comment] 2020-03-18 10:23
i have same issue:

```
2020-03-14 08:43:11 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 211, in async_setup_platform
    self.hass, self.config, self.domain, platform_type
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in async_prepare_setup_platform
    integration = await loader.async_get_integration(hass, platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 323, in async_get_integration
    Integration.resolve_from_root, hass, components, domain
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 156, in resolve_from_root
    manifest_path = pathlib.Path(base) / domain / "manifest.json"
  File "/usr/local/lib/python3.7/pathlib.py", line 920, in __truediv__
    return self._make_child((key,))
  File "/usr/local/lib/python3.7/pathlib.py", line 699, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.7/pathlib.py", line 653, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by bongiozzo** [comment] 2020-03-29 14:57
Also have this error with var: in configuration.

Don't know - may be this link will be useful
https://community.home-assistant.io/t/error-doing-job/154622/2

**Comment by snarky-snark** [comment] 2020-03-29 17:44
Ah, thanks! That might be the issue.

**Comment by snarky-snark** [comment] 2020-04-03 18:10
I'm getting reports that this is a breaking bug in HA 0.108.0b0.

**Comment by snarky-snark** [comment] 2020-04-03 18:13
Anyone want to try adding the platform to their variable setup to see if that fixes things?

```yaml
var:
  foo:
    platform: var
    initial_value: "bar"
    ... 
```

or 

```yaml
var foo:
  platform: var
  initial_value: "bar"
  ... 
```

**Comment by jazzyisj** [comment] 2020-04-03 19:50
Changing my var config to this.

```
base_url:
  platform: var
  initial_value: !secret BASE_URL
current_house_alarm:
  platform: var
  friendly_name: "Current Alarm Alert"
  icon: mdi:shield-alert
  restore: true
alarm_triggered:
  platform: var
  friendly_name: "Alarm Triggered"
  icon: mdi:alarm
  restore: true
```

Results in this.

`Invalid config for [var]: [platform] is an invalid option for [var]. Check: var->var->base_url->platform. (See /config/configuration.yaml, line 121)`

**Comment by jazzyisj** [comment] 2020-04-03 20:42
This doesn't work either.
```
var: 
  - platform: var
    base_url:
      initial_value: !secret BASE_URL
```
Results.

`nvalid config for [var]: expected a dictionary for dictionary value @ data['var']. Got [OrderedDict([('platform', 'var'), ('base_url', OrderedDict([('initial_value', '<redacted>')]))])]. (See /config/configuration.yaml, line 123). `

**Comment by snarky-snark** [comment] 2020-04-03 20:44
Dang. Thanks for trying it. I'm still not sure how to deal with this. Home Assistant docs aren't very helpful for this.

**Comment by jazzyisj** [comment] 2020-04-03 20:55
I wouldn't even know where to start.  Wish I could help.  I've googled the hell out of it trust me.  This will be a very bad breaking change for me I have 30ish some odd variables! 

Have you tried reaching out to any of the superstar integration developers to pick their brains?  Hopefully it's just something simple that got overlooked.

**Comment by Swiftnesses** [comment] 2020-04-08 10:23
I rolled back to the last stable release to get the component working again.

As the new release will become stable soon - I expect this component will be broken for all users that upgrade, until a fix is found.

**Closed** 2020-04-08 13:52 UTC
Labels: bug, reported-in:0.7.0
